#pragma once

#if IDC_LINE_RECIPE_NAME1+1 == IDC_LINE_RECIPE_NAME2 && \
	IDC_LINE_RECIPE_NAME2+1 == IDC_LINE_RECIPE_NAME3 && \
	IDC_LINE_RECIPE_NAME3+1 == IDC_LINE_RECIPE_NAME4 && \
	IDC_LINE_RECIPE_NAME4+1 == IDC_LINE_RECIPE_NAME5 && \
	IDC_LINE_RECIPE_NAME5+1 == IDC_LINE_RECIPE_NAME6 && \
	IDC_LINE_RECIPE_NAME6+1 == IDC_LINE_RECIPE_NAME7 && \
	IDC_LINE_RECIPE_NAME7+1 == IDC_LINE_RECIPE_NAME8 
#else
#error "IDC_LINE_RECIPE_NAME1+1 != IDC_LINE_RECIPE_NAME2"
#endif

#if IDC_LINE_RECIPE_NR1+1 == IDC_LINE_RECIPE_NR2 && \
	IDC_LINE_RECIPE_NR2+1 == IDC_LINE_RECIPE_NR3 && \
	IDC_LINE_RECIPE_NR3+1 == IDC_LINE_RECIPE_NR4 && \
	IDC_LINE_RECIPE_NR4+1 == IDC_LINE_RECIPE_NR5 && \
	IDC_LINE_RECIPE_NR5+1 == IDC_LINE_RECIPE_NR6 && \
	IDC_LINE_RECIPE_NR6+1 == IDC_LINE_RECIPE_NR7 && \
	IDC_LINE_RECIPE_NR7+1 == IDC_LINE_RECIPE_NR8 
#else
#error "IDC_LINE_RECIPE_NR1+1 != IDC_LINE_RECIPE_NR2"
#endif

#if IDC_LINE_RECIPE_QMNUMBER1+1 == IDC_LINE_RECIPE_QMNUMBER2 && \
	IDC_LINE_RECIPE_QMNUMBER2+1 == IDC_LINE_RECIPE_QMNUMBER3 && \
	IDC_LINE_RECIPE_QMNUMBER3+1 == IDC_LINE_RECIPE_QMNUMBER4 && \
	IDC_LINE_RECIPE_QMNUMBER4+1 == IDC_LINE_RECIPE_QMNUMBER5 && \
	IDC_LINE_RECIPE_QMNUMBER5+1 == IDC_LINE_RECIPE_QMNUMBER6 && \
	IDC_LINE_RECIPE_QMNUMBER6+1 == IDC_LINE_RECIPE_QMNUMBER7 && \
	IDC_LINE_RECIPE_QMNUMBER7+1 == IDC_LINE_RECIPE_QMNUMBER8 
#else
#error "IDC_LINE_RECIPE_QMNUMBER1+1 != IDC_LINE_RECIPE_QMNUMBER2"
#endif

#if IDC_LINE_RECIPE_DOSIERTYP1+1 == IDC_LINE_RECIPE_DOSIERTYP2 && \
	IDC_LINE_RECIPE_DOSIERTYP2+1 == IDC_LINE_RECIPE_DOSIERTYP3 && \
	IDC_LINE_RECIPE_DOSIERTYP3+1 == IDC_LINE_RECIPE_DOSIERTYP4 && \
	IDC_LINE_RECIPE_DOSIERTYP4+1 == IDC_LINE_RECIPE_DOSIERTYP5 && \
	IDC_LINE_RECIPE_DOSIERTYP5+1 == IDC_LINE_RECIPE_DOSIERTYP6 && \
	IDC_LINE_RECIPE_DOSIERTYP6+1 == IDC_LINE_RECIPE_DOSIERTYP7 && \
	IDC_LINE_RECIPE_DOSIERTYP7+1 == IDC_LINE_RECIPE_DOSIERTYP8 
#else
#error "IDC_LINE_RECIPE_DOSIERTYP1+1 != IDC_LINE_RECIPE_DOSIERTYP2"
#endif


#if IDC_LINE_RECIPE_REGENERAT1+1 == IDC_LINE_RECIPE_REGENERAT2 && \
	IDC_LINE_RECIPE_REGENERAT2+1 == IDC_LINE_RECIPE_REGENERAT3 && \
	IDC_LINE_RECIPE_REGENERAT3+1 == IDC_LINE_RECIPE_REGENERAT4 && \
	IDC_LINE_RECIPE_REGENERAT4+1 == IDC_LINE_RECIPE_REGENERAT5 && \
	IDC_LINE_RECIPE_REGENERAT5+1 == IDC_LINE_RECIPE_REGENERAT6 && \
	IDC_LINE_RECIPE_REGENERAT6+1 == IDC_LINE_RECIPE_REGENERAT7 && \
	IDC_LINE_RECIPE_REGENERAT7+1 == IDC_LINE_RECIPE_REGENERAT8 
#else
#error "IDC_LINE_RECIPE_REGENERAT1+1 != IDC_LINE_RECIPE_REGENERAT2"
#endif

#if IDC_LINE_RECIPE_PERCENTAGE1+1 == IDC_LINE_RECIPE_PERCENTAGE2 && \
	IDC_LINE_RECIPE_PERCENTAGE2+1 == IDC_LINE_RECIPE_PERCENTAGE3 && \
	IDC_LINE_RECIPE_PERCENTAGE3+1 == IDC_LINE_RECIPE_PERCENTAGE4 && \
	IDC_LINE_RECIPE_PERCENTAGE4+1 == IDC_LINE_RECIPE_PERCENTAGE5 && \
	IDC_LINE_RECIPE_PERCENTAGE5+1 == IDC_LINE_RECIPE_PERCENTAGE6 && \
	IDC_LINE_RECIPE_PERCENTAGE6+1 == IDC_LINE_RECIPE_PERCENTAGE7 && \
	IDC_LINE_RECIPE_PERCENTAGE7+1 == IDC_LINE_RECIPE_PERCENTAGE8 
#else
#error "IDC_LINE_RECIPE_PERCENTAGE1+1 != IDC_LINE_RECIPE_PERCENTAGE2"
#endif

#if IDC_LINE_RECIPE_SETPOINT1+1 == IDC_LINE_RECIPE_SETPOINT2 && \
	IDC_LINE_RECIPE_SETPOINT2+1 == IDC_LINE_RECIPE_SETPOINT3 && \
	IDC_LINE_RECIPE_SETPOINT3+1 == IDC_LINE_RECIPE_SETPOINT4 && \
	IDC_LINE_RECIPE_SETPOINT4+1 == IDC_LINE_RECIPE_SETPOINT5 && \
	IDC_LINE_RECIPE_SETPOINT5+1 == IDC_LINE_RECIPE_SETPOINT6 && \
	IDC_LINE_RECIPE_SETPOINT6+1 == IDC_LINE_RECIPE_SETPOINT7 && \
	IDC_LINE_RECIPE_SETPOINT7+1 == IDC_LINE_RECIPE_SETPOINT8 
#else
#error "IDC_LINE_RECIPE_SETPOINT1+1 != IDC_LINE_RECIPE_SETPOINT2"
#endif


//-----------------------------------------------------------------------------------------------------
#if IDC_RECIPE_SETPOINT1+1 == IDC_RECIPE_SETPOINT2 && \
	IDC_RECIPE_SETPOINT2+1 == IDC_RECIPE_SETPOINT3 && \
	IDC_RECIPE_SETPOINT3+1 == IDC_RECIPE_SETPOINT4 && \
	IDC_RECIPE_SETPOINT4+1 == IDC_RECIPE_SETPOINT5 && \
	IDC_RECIPE_SETPOINT5+1 == IDC_RECIPE_SETPOINT6 && \
	IDC_RECIPE_SETPOINT6+1 == IDC_RECIPE_SETPOINT7 && \
	IDC_RECIPE_SETPOINT7+1 == IDC_RECIPE_SETPOINT8 
#else
#error "IDC_RECIPE_SETPOINT1+1 != IDC_RECIPE_SETPOINT2"
#endif


#if IDC_RECIPE_NAME1+1 == IDC_RECIPE_NAME2 && \
	IDC_RECIPE_NAME2+1 == IDC_RECIPE_NAME3 && \
	IDC_RECIPE_NAME3+1 == IDC_RECIPE_NAME4 && \
	IDC_RECIPE_NAME4+1 == IDC_RECIPE_NAME5 && \
	IDC_RECIPE_NAME5+1 == IDC_RECIPE_NAME6 && \
	IDC_RECIPE_NAME6+1 == IDC_RECIPE_NAME7 && \
	IDC_RECIPE_NAME7+1 == IDC_RECIPE_NAME8 
#else
#error "IDC_RECIPE_NAME1+1 != IDC_RECIPE_NAME2"
#endif


#if IDC_RECIPE_NR1+1 == IDC_RECIPE_NR2 && \
	IDC_RECIPE_NR2+1 == IDC_RECIPE_NR3 && \
	IDC_RECIPE_NR3+1 == IDC_RECIPE_NR4 && \
	IDC_RECIPE_NR4+1 == IDC_RECIPE_NR5 && \
	IDC_RECIPE_NR5+1 == IDC_RECIPE_NR6 && \
	IDC_RECIPE_NR6+1 == IDC_RECIPE_NR7 && \
	IDC_RECIPE_NR7+1 == IDC_RECIPE_NR8 
#else
#error "IDC_RECIPE_NR1+1 != IDC_RECIPE_NR2"
#endif


#if IDC_RECIPE_QMNUMBER1+1 == IDC_RECIPE_QMNUMBER2 && \
	IDC_RECIPE_QMNUMBER2+1 == IDC_RECIPE_QMNUMBER3 && \
	IDC_RECIPE_QMNUMBER3+1 == IDC_RECIPE_QMNUMBER4 && \
	IDC_RECIPE_QMNUMBER4+1 == IDC_RECIPE_QMNUMBER5 && \
	IDC_RECIPE_QMNUMBER5+1 == IDC_RECIPE_QMNUMBER6 && \
	IDC_RECIPE_QMNUMBER6+1 == IDC_RECIPE_QMNUMBER7 && \
	IDC_RECIPE_QMNUMBER7+1 == IDC_RECIPE_QMNUMBER8 
#else
#error "IDC_RECIPE_QMNUMBER1+1 != IDC_RECIPE_QMNUMBER2"
#endif

#if IDC_RECIPE_DOSIERTYP1+1 == IDC_RECIPE_DOSIERTYP2 && \
	IDC_RECIPE_DOSIERTYP2+1 == IDC_RECIPE_DOSIERTYP3 && \
	IDC_RECIPE_DOSIERTYP3+1 == IDC_RECIPE_DOSIERTYP4 && \
	IDC_RECIPE_DOSIERTYP4+1 == IDC_RECIPE_DOSIERTYP5 && \
	IDC_RECIPE_DOSIERTYP5+1 == IDC_RECIPE_DOSIERTYP6 && \
	IDC_RECIPE_DOSIERTYP6+1 == IDC_RECIPE_DOSIERTYP7 && \
	IDC_RECIPE_DOSIERTYP7+1 == IDC_RECIPE_DOSIERTYP8 
#else
#error "IDC_RECIPE_DOSIERTYP1+1 != IDC_RECIPE_DOSIERTYP2"
#endif

#if IDC_RECIPE_REGENERAT1+1 == IDC_RECIPE_REGENERAT2 && \
	IDC_RECIPE_REGENERAT2+1 == IDC_RECIPE_REGENERAT3 && \
	IDC_RECIPE_REGENERAT3+1 == IDC_RECIPE_REGENERAT4 && \
	IDC_RECIPE_REGENERAT4+1 == IDC_RECIPE_REGENERAT5 && \
	IDC_RECIPE_REGENERAT5+1 == IDC_RECIPE_REGENERAT6 && \
	IDC_RECIPE_REGENERAT6+1 == IDC_RECIPE_REGENERAT7 && \
	IDC_RECIPE_REGENERAT7+1 == IDC_RECIPE_REGENERAT8 
#else
#error "IDC_RECIPE_REGENERAT1+1 != IDC_RECIPE_REGENERAT2"
#endif

#if IDC_RECIPE_PERCENTAGE1+1 == IDC_RECIPE_PERCENTAGE2 && \
	IDC_RECIPE_PERCENTAGE2+1 == IDC_RECIPE_PERCENTAGE3 && \
	IDC_RECIPE_PERCENTAGE3+1 == IDC_RECIPE_PERCENTAGE4 && \
	IDC_RECIPE_PERCENTAGE4+1 == IDC_RECIPE_PERCENTAGE5 && \
	IDC_RECIPE_PERCENTAGE5+1 == IDC_RECIPE_PERCENTAGE6 && \
	IDC_RECIPE_PERCENTAGE6+1 == IDC_RECIPE_PERCENTAGE7 && \
	IDC_RECIPE_PERCENTAGE7+1 == IDC_RECIPE_PERCENTAGE8 
#else
#error "IDC_RECIPE_PERCENTAGE1+1 != IDC_RECIPE_PERCENTAGE2"
#endif


#if IDC_RECIPE_REFILL_MINMIN1+1 == IDC_RECIPE_REFILL_MINMIN2 && \
	IDC_RECIPE_REFILL_MINMIN2+1 == IDC_RECIPE_REFILL_MINMIN3 && \
	IDC_RECIPE_REFILL_MINMIN3+1 == IDC_RECIPE_REFILL_MINMIN4 && \
	IDC_RECIPE_REFILL_MINMIN4+1 == IDC_RECIPE_REFILL_MINMIN5 && \
	IDC_RECIPE_REFILL_MINMIN5+1 == IDC_RECIPE_REFILL_MINMIN6 && \
	IDC_RECIPE_REFILL_MINMIN6+1 == IDC_RECIPE_REFILL_MINMIN7 && \
	IDC_RECIPE_REFILL_MINMIN7+1 == IDC_RECIPE_REFILL_MINMIN8 
#else
#error "IDC_RECIPE_REFILL_MINMIN1+1 != IDC_RECIPE_REFILL_MINMIN2"
#endif


#if IDC_RECIPE_REFILL_MIN1+1 == IDC_RECIPE_REFILL_MIN2 && \
	IDC_RECIPE_REFILL_MIN2+1 == IDC_RECIPE_REFILL_MIN3 && \
	IDC_RECIPE_REFILL_MIN3+1 == IDC_RECIPE_REFILL_MIN4 && \
	IDC_RECIPE_REFILL_MIN4+1 == IDC_RECIPE_REFILL_MIN5 && \
	IDC_RECIPE_REFILL_MIN5+1 == IDC_RECIPE_REFILL_MIN6 && \
	IDC_RECIPE_REFILL_MIN6+1 == IDC_RECIPE_REFILL_MIN7 && \
	IDC_RECIPE_REFILL_MIN7+1 == IDC_RECIPE_REFILL_MIN8 
#else
#error "IDC_RECIPE_REFILL_MIN1+1 != IDC_RECIPE_REFILL_MIN2"
#endif


#if IDC_RECIPE_REFILL_MAX1+1 == IDC_RECIPE_REFILL_MAX2 && \
	IDC_RECIPE_REFILL_MAX2+1 == IDC_RECIPE_REFILL_MAX3 && \
	IDC_RECIPE_REFILL_MAX3+1 == IDC_RECIPE_REFILL_MAX4 && \
	IDC_RECIPE_REFILL_MAX4+1 == IDC_RECIPE_REFILL_MAX5 && \
	IDC_RECIPE_REFILL_MAX5+1 == IDC_RECIPE_REFILL_MAX6 && \
	IDC_RECIPE_REFILL_MAX6+1 == IDC_RECIPE_REFILL_MAX7 && \
	IDC_RECIPE_REFILL_MAX7+1 == IDC_RECIPE_REFILL_MAX8 
#else
#error "IDC_RECIPE_REFILL_MAX1+1 != IDC_RECIPE_REFILL_MAX2"
#endif

#if IDC_RECIPE_DOSEFACTOR1+1 == IDC_RECIPE_DOSEFACTOR2 && \
	IDC_RECIPE_DOSEFACTOR2+1 == IDC_RECIPE_DOSEFACTOR3 && \
	IDC_RECIPE_DOSEFACTOR3+1 == IDC_RECIPE_DOSEFACTOR4 && \
	IDC_RECIPE_DOSEFACTOR4+1 == IDC_RECIPE_DOSEFACTOR5 && \
	IDC_RECIPE_DOSEFACTOR5+1 == IDC_RECIPE_DOSEFACTOR6 && \
	IDC_RECIPE_DOSEFACTOR6+1 == IDC_RECIPE_DOSEFACTOR7 && \
	IDC_RECIPE_DOSEFACTOR7+1 == IDC_RECIPE_DOSEFACTOR8 
#else
#error "IDC_RECIPE_DOSEFACTOR1+1 != IDC_RECIPE_DOSEFACTOR2"
#endif


